#!/bin/bash

time g++ -std=c++2a \
        -I"/home/vittorioromeo/OHWorkspace/ecst/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_pp/include" \
        -W -Wall -Wextra -Wpedantic \
        -Ofast -ffast-math -ftree-vectorize -DNDEBUG \
        -lpthread \
        -lsfml-system -lsfml-graphics -lsfml-window \
        -fdiagnostics-color=always \
        $1 -o /tmp/x.x |& ./ecst_camomilla.sh

if [ $? == 0 ]; then
    echo "Compiled." && /tmp/x.x "${@:2}"
else
    echo "Failed."
fi
