#!/bin/bash

time g++ -std=c++14 \
        -I"/home/vittorioromeo/OHWorkspace/ecst/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_pp/include" \
        -W \
        -Wall \
        -Wextra \
        -O2 \
        -pedantic \
        -DNDEBUG \
        -lpthread \
        -lsfml-system \
        -lsfml-graphics \
        -lsfml-window \
        $1 -o /tmp/x.x |& camomilla

if [ $? == 0 ]; then
    echo "Compiled." && primusrun /tmp/x.x "${@:2}"
else
    echo "Failed."
fi
