#!/bin/bash 

g++ -std=c++14 \
        -D_GLIBCXX_DEBUG \
        -fsanitize=undefined \
        -I"/home/vittorioromeo/OHWorkspace/ecs_thesis/project/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_pp/include" \
        -O0 \
        -pedantic \
        -W \
        -Wall \
        -Wextra \
        -lpthread \
        -lboost_system \
        -lboost_thread \
        -lsfml-system \
        -lsfml-graphics \
        -lsfml-window \
        -g3 \
        $1 -o /tmp/x.x && echo "Compiled." && gdb /tmp/x.x "${@:2}"