#!/bin/bash

g++ -std=c++14 \
        -I"/home/vittorioromeo/OHWorkspace/ecs_thesis/project/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_pp/include" \
        -g \
        -Og \
        -pedantic \
        -W \
        -Wall \
        -Wextra \
        -lpthread \
        -Wno-unused-variable \
        $1 -o /tmp/x.x && echo "Compiled." && /tmp/x.x "${@:2}"
