#!/bin/bash

time g++ -std=c++14 \
        -I"/home/vittorioromeo/OHWorkspace/ecs_thesis/project/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_core/include" \
        -I"/home/vittorioromeo/OHWorkspace/vrm_pp/include" \
        -W \
        -Wall \
        -Wextra \
        -Ofast \
        -ffast-math \
        -pedantic \
        -DNDEBUG \
        -lpthread \
        -lsfml-system \
        -lsfml-graphics \
        -lsfml-window \
        -g \
        -march=native \
        $1 -o /tmp/x.x && echo "Compiled." && /tmp/x.x "${@:2}"
